# Generated by Django 4.1.4 on 2023-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
