# Generated by Django 4.1.4 on 2023-12-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Author",
            },
        ),
    ]
