import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ResponsiveAppBar from "./components/navbar/page";
import Home from "./home/page";
import CustomizedAccordions from "./faq/page";
import Footer from "./footer/page";
import About from "./about/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resto Keluarga Solo",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveAppBar />
        <Home />
        <About />
        <CustomizedAccordions id={0} question={""} answer={""} />
        <Footer />

        {children}
      </body>
    </html>
  );
}
