import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ResponsiveAppBar from "./components/navbar";
import About from "./home/page";
import CustomizedAccordions from "./faq/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resto Keluarga Solo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveAppBar />
        <About />
        <CustomizedAccordions />

        {children}
      </body>
    </html>
  );
}
