import type { Metadata } from "next";
import Navbar from "./components/navbar";

import { Inter } from "next/font/google";
import "./globals.css";
import About from "./about/page";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resto Keluarga Solo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <About />
        <Footer />

        {children}
      </body>
    </html>
  );
}
