# Generated by Django 4.1.4 on 2023-12-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_authordetail_delete_menudetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuthorDetail",
            new_name="Author",
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Author"},
        ),
    ]
