# Generated by Django 4.1.4 on 2023-12-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_rename_authordetail_author_alter_author_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
